name: Test CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"

jobs:
  test-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/local/lib/android /opt/ghc /usr/share/dotnet
          df -h

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Check up flake configuration
        run: nix flake check --all-systems --show-trace

  build-nixos:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        hostname: [desktop, laptop, vm]

    steps:
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/local/lib/android /opt/ghc /usr/share/dotnet
          df -h

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build NixOS configuration
        run: nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel --show-trace
